// <auto-generated />
namespace Chauffer.Web.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Edited_TotalCharge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edited_TotalCharge));
        
        string IMigrationMetadata.Id
        {
            get { return "201807222004453_Edited_TotalCharge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
